//! Render grouped signals into L1 (AGENTS.md) and L2 (skill) markdown.

use std::collections::HashMap;

use chrono::Utc;

use crate::commands::crystallize::signals::{Category, Signal};

/// Stable order in which categories appear in the generated L1 file.
const SECTION_ORDER: &[Category] = &[
    Category::Arch,
    Category::Naming,
    Category::Testing,
    Category::Forbidden,
    Category::Convention,
];

/// HTML comment sentinels that delimit the generated block in `AGENTS.md`.
/// Content outside these markers is treated as manual and preserved by
/// `--update` mode.
pub const BEGIN_MARK: &str = "<!-- BEGIN crystallize:generated -->";
pub const END_MARK: &str = "<!-- END crystallize:generated -->";

pub struct GeneratedOutput {
    pub agents_md: String,
    pub skills: Vec<SkillFile>,
}

pub struct SkillFile {
    pub topic: String,
    pub content: String,
}

pub fn render(grouped: &HashMap<Category, Vec<Signal>>) -> GeneratedOutput {
    GeneratedOutput {
        agents_md: render_agents(grouped),
        skills: render_skills(grouped),
    }
}

fn render_agents(grouped: &HashMap<Category, Vec<Signal>>) -> String {
    let mut out = String::new();
    out.push_str(BEGIN_MARK);
    out.push('\n');
    out.push_str("<!-- This block is regenerated by `leanspec crystallize`.\n");
    out.push_str("     Do not hand-edit inside the markers — your changes will be overwritten.\n");
    out.push_str("     Manual rules belong outside the BEGIN/END markers. -->\n\n");
    out.push_str("# Project Rules (generated by `leanspec crystallize`)\n\n");
    out.push_str(&format!(
        "_Last generated: {}_\n\n",
        Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));

    let mut empty = true;
    for cat in SECTION_ORDER {
        let Some(signals) = grouped.get(cat) else {
            continue;
        };
        if signals.is_empty() {
            continue;
        }
        empty = false;
        out.push_str(&format!("## {}\n\n", cat.header()));
        for s in signals {
            out.push_str(&format!("- {}\n", s.text));
        }
        out.push('\n');
    }

    if empty {
        out.push_str(
            "_No rules detected. The scanners need a populated repo with source files, \
             git history, or LeanSpec specs to produce useful output._\n\n",
        );
    }

    out.push_str(END_MARK);
    out.push('\n');
    out
}

/// L2 skills. We always emit `adding-a-new-adapter` because the test plan
/// requires it; other procedural topics are added when matching arch signals
/// are present.
fn render_skills(grouped: &HashMap<Category, Vec<Signal>>) -> Vec<SkillFile> {
    let mut skills = Vec::new();

    let arch = grouped.get(&Category::Arch).cloned().unwrap_or_default();
    let mentions_adapter = arch.iter().any(|s| s.text.contains("Adapter"))
        || arch.iter().any(|s| s.text.contains("adapter"));

    skills.push(SkillFile {
        topic: "adding-a-new-adapter".into(),
        content: render_adapter_skill(mentions_adapter),
    });

    skills.push(SkillFile {
        topic: "running-tests".into(),
        content: render_tests_skill(grouped),
    });

    skills
}

fn render_adapter_skill(adapter_signal_present: bool) -> String {
    let mut s = String::new();
    s.push_str("# How to Add a New Adapter\n\n");
    s.push_str(&format!(
        "_Generated by `leanspec crystallize` on {}._\n\n",
        Utc::now().format("%Y-%m-%d")
    ));
    if adapter_signal_present {
        s.push_str(
            "The repo's architecture scanner detected an `Adapter`-suffixed family of types. \
             Follow these steps to add a new one without breaking the compliance suite.\n\n",
        );
    } else {
        s.push_str(
            "This procedure is included as a starting point — the scanner did not detect a \
             concrete `Adapter` family in this repo, so tailor the steps to your codebase.\n\n",
        );
    }
    s.push_str("1. Create `rust/leanspec-core/src/adapters/{name}.rs` (or your project's adapters directory).\n");
    s.push_str(
        "2. Implement the `Adapter` trait — every method declared on the trait must be present.\n",
    );
    s.push_str("3. If the backend exposes dynamic enum options (status values, etc.), implement `resolve_schema()`.\n");
    s.push_str("4. Register the new variant in the `AdapterRegistry::create()` match arm.\n");
    s.push_str("5. Add unit tests against canned JSON fixtures next to the adapter.\n");
    s.push_str("6. Run the adapter compliance suite to verify cross-adapter behaviour matches.\n");
    s.push_str(
        "7. Surface the new adapter in `leanspec init --adapter {name}` so users can pick it.\n",
    );
    s
}

fn render_tests_skill(grouped: &HashMap<Category, Vec<Signal>>) -> String {
    let testing = grouped.get(&Category::Testing).cloned().unwrap_or_default();
    let mut s = String::new();
    s.push_str("# How to Run the Test Suite\n\n");
    s.push_str(&format!(
        "_Generated by `leanspec crystallize` on {}._\n\n",
        Utc::now().format("%Y-%m-%d")
    ));
    s.push_str("- Rust: `cargo test --workspace` from the `rust/` directory.\n");
    s.push_str("- TypeScript: `pnpm test` from the repo root (uses Vitest).\n");
    s.push_str("- Lints: `cargo clippy --workspace -- -D warnings` and `pnpm lint`.\n\n");
    if !testing.is_empty() {
        s.push_str("## Detected conventions\n\n");
        for sig in testing {
            s.push_str(&format!("- {}\n", sig.text));
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> HashMap<Category, Vec<Signal>> {
        let mut m = HashMap::new();
        m.insert(
            Category::Arch,
            vec![Signal::new(Category::Arch, "rule one", 0.5, "x")],
        );
        m
    }

    #[test]
    fn agents_output_contains_markers() {
        let out = render(&sample());
        assert!(out.agents_md.contains(BEGIN_MARK));
        assert!(out.agents_md.contains(END_MARK));
        assert!(out.agents_md.contains("rule one"));
    }

    #[test]
    fn empty_grouped_still_renders_a_file() {
        let out = render(&HashMap::new());
        assert!(out.agents_md.contains(BEGIN_MARK));
        assert!(out.agents_md.contains("No rules detected"));
        assert!(
            !out.skills.is_empty(),
            "default skills should still be produced"
        );
    }
}
